from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from .schemas import CandidateKhoan, SocialPost, TopicResult, LinkCandidate, NliResult, BriefDraft, SuggestDraft


@runtime_checkable
class VectorClient(Protocol):
    async def search(self, collection: str, vector: list[float], *, limit: int, query_filter: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    async def upsert(self, collection: str, points: list[dict[str, Any]]) -> None: ...
    async def get_collection(self, collection: str) -> dict[str, Any]: ...


@runtime_checkable
class SocialRepository(Protocol):
    async def upsert_post(self, post: SocialPost) -> str: ...
    async def get_post(self, bai_dang_id: str) -> SocialPost | None: ...
    async def save_topic(self, result: TopicResult) -> None: ...
    async def get_topic(self, bai_dang_id: str) -> TopicResult | None: ...
    async def create_link_edge(self, bai_dang_id: str, candidate: LinkCandidate, *, method: str) -> None: ...
    async def save_nli(self, bai_dang_id: str, khoan_id: str, result: NliResult) -> None: ...
    async def save_alert(self, alert: dict[str, Any]) -> str: ...
    async def find_recent_alert(self, key: str, cooldown_s: int) -> dict[str, Any] | None: ...


@runtime_checkable
class LegalRepository(Protocol):
    async def get_khoan(self, khoan_id: str) -> CandidateKhoan | None: ...
    async def get_khoan_many(self, khoan_ids: list[str]) -> list[CandidateKhoan]: ...
    async def list_khoan_for_van_ban(self, van_ban_id: str) -> list[CandidateKhoan]: ...


@runtime_checkable
class ContentRepository(Protocol):
    async def save_brief(self, draft: BriefDraft) -> str: ...
    async def save_suggestion(self, draft: SuggestDraft) -> str: ...
    async def load_alerts(self, alert_ids: list[str]) -> list[dict[str, Any]]: ...


@runtime_checkable
class LLMClient(Protocol):
    async def complete(self, *, route: str, model: str, task: str, prompt: str, timeout_s: float) -> dict[str, Any]: ...
    async def health(self) -> dict[str, Any]: ...
